version: '3.8'

services:
  backend:
    # Você escreve o SEU usuário aqui:
    image: flipq/todostreak-back:latest
    ports:
      - "8000:8000"

  frontend:
    # E aqui também:
    image: flipq/todostreak-front:latest
    ports:
      - "8080:80"
    depends_on:
      - backend